/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial.pkg3.prog.pkg4;

import javax.swing.JOptionPane;

/**
 *
 * @author yahir
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cbxCategorias = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cbxCarnes = new javax.swing.JComboBox<>();
        cbxAbarrotes = new javax.swing.JComboBox<>();
        cbxCarnesFrias = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        cbxDescuentos = new javax.swing.JComboBox<>();
        cbxIVA = new javax.swing.JComboBox<>();
        cbxUnidades = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUnidades = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblUnidad = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAgregar = new javax.swing.JMenu();
        mnuAagregar = new javax.swing.JMenuItem();
        mnuAcomprar = new javax.swing.JMenuItem();
        mnuAsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 350));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        jPanel7.setLayout(new java.awt.GridLayout(3, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9);

        cbxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un Producto", "Carnes", "Abarrotes", "Carnes frias " }));
        cbxCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriasActionPerformed(evt);
            }
        });
        jPanel7.add(cbxCategorias);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel10);

        jPanel4.add(jPanel7);

        jPanel8.setEnabled(false);
        jPanel8.setLayout(new java.awt.GridLayout(3, 1));

        cbxCarnes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Res", "Puerco", "Pollo", "Pezcado " }));
        cbxCarnes.setEnabled(false);
        jPanel8.add(cbxCarnes);

        cbxAbarrotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azucar", "Sal", "Harina", "Huevo" }));
        cbxAbarrotes.setEnabled(false);
        jPanel8.add(cbxAbarrotes);

        cbxCarnesFrias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jamon", "Salchicha", "Queso de puerco", "Chuleta" }));
        cbxCarnesFrias.setEnabled(false);
        jPanel8.add(cbxCarnesFrias);

        jPanel4.add(jPanel8);

        jPanel6.setEnabled(false);
        jPanel6.setLayout(new java.awt.GridLayout(3, 1));

        cbxDescuentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "15%" }));
        cbxDescuentos.setEnabled(false);
        jPanel6.add(cbxDescuentos);

        cbxIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12%", "16%", "20%" }));
        cbxIVA.setEnabled(false);
        jPanel6.add(cbxIVA);

        cbxUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pieza", "kilo", "Gramos" }));
        cbxUnidades.setEnabled(false);
        jPanel6.add(cbxUnidades);

        jPanel4.add(jPanel6);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jPanel12.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tipo de producto");
        jPanel12.add(jLabel1);

        lblTipo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(lblTipo);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Descripcion del producto");
        jPanel12.add(jLabel6);

        lblDescripcion.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(lblDescripcion);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Descuentos o uniades");
        jPanel12.add(jLabel3);

        lblUnidades.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lblUnidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(lblUnidades);

        jPanel5.add(jPanel12);

        jPanel11.setLayout(new java.awt.GridLayout(3, 2));

        jLabel2.setText("Precio");
        jPanel11.add(jLabel2);

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel11.add(txtPrecio);

        lblUnidad.setText("Peso");
        jPanel11.add(lblUnidad);

        txtPeso.setEnabled(false);
        jPanel11.add(txtPeso);

        jLabel5.setText("Subtotal");
        jPanel11.add(jLabel5);
        jPanel11.add(lblSubtotal);

        jPanel5.add(jPanel11);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        mnuAgregar.setText("Archivo");

        mnuAagregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuAagregar.setText("Agregar");
        mnuAagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAagregarActionPerformed(evt);
            }
        });
        mnuAgregar.add(mnuAagregar);

        mnuAcomprar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuAcomprar.setText("Comprar");
        mnuAcomprar.setEnabled(false);
        mnuAcomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcomprarActionPerformed(evt);
            }
        });
        mnuAgregar.add(mnuAcomprar);

        mnuAsalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuAsalir.setText("Salir");
        mnuAsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAsalirActionPerformed(evt);
            }
        });
        mnuAgregar.add(mnuAsalir);

        jMenuBar1.add(mnuAgregar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriasActionPerformed
        // TODO add your handling code here:

        if (cbxCategorias.getSelectedItem() == "Carnes") {
            cbxCarnes.enable(true);
            cbxAbarrotes.enable(false);
            cbxCarnesFrias.enable(false);
            cbxDescuentos.setEnabled(true);
            cbxIVA.setEnabled(false);
            cbxUnidades.setEnabled(false);
        }
        if (cbxCategorias.getSelectedItem() == "Abarrotes") {
            cbxCarnes.enable(false);
            cbxAbarrotes.enable(true);
            cbxCarnesFrias.enable(false);
            cbxDescuentos.setEnabled(false);
            cbxIVA.setEnabled(true);
            cbxUnidades.setEnabled(false);
        }
        if (cbxCategorias.getSelectedItem() == "Carnes frias ") {
            cbxCarnes.enable(false);
            cbxAbarrotes.enable(false);
            cbxCarnesFrias.enable(true);
            cbxDescuentos.setEnabled(false);
            cbxIVA.setEnabled(false);
            cbxUnidades.setEnabled(true);
        }
    }//GEN-LAST:event_cbxCategoriasActionPerformed

    private void mnuAcomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcomprarActionPerformed
        // TODO add your handling code here:
        if (txtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Escriibe el precio del producto");
        } else {
            if (cbxCategorias.getSelectedItem() == "Carnes") {
                int precio = Integer.parseInt(txtPrecio.getText());
                String de = (String) cbxDescuentos.getSelectedItem();
                de = de.substring(0, de.length() - 1);
                float st = precio - (precio * (Float.parseFloat(de) / 100));
                lblSubtotal.setText(Float.toString(st));
            }
            if (cbxCategorias.getSelectedItem() == "Abarrotes") {
                int precio = Integer.parseInt(txtPrecio.getText());
                String de = (String) cbxIVA.getSelectedItem();
                de = de.substring(0, de.length() - 1);
                float st = precio + (precio * (Float.parseFloat(de) / 100));
                lblSubtotal.setText(Float.toString(st));
            }
            if (cbxCategorias.getSelectedItem() == "Carnes frias ") {
                if (txtPeso.getText().isEmpty()){
                  JOptionPane.showMessageDialog(null, "Elige un peso");
                }else{
                int precio = Integer.parseInt(txtPrecio.getText());
                String de = (String) cbxIVA.getSelectedItem();
               // de = de.substring(0, de.length() - 1);
                float peso = Float.parseFloat(txtPeso.getText());
                float st = precio * peso;
                lblSubtotal.setText(Float.toString(st));
                }
            }

        }

    }//GEN-LAST:event_mnuAcomprarActionPerformed

    private void mnuAagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAagregarActionPerformed
        // TODO add your handling code here:
        if (cbxCategorias.getSelectedItem() == "Elige un Producto") {
            JOptionPane.showMessageDialog(null, "Error, Elige un producto");
        } else {
            if (cbxCategorias.getSelectedItem() == "Carnes") {
                String tipo = (String) cbxCategorias.getSelectedItem();
                lblTipo.setText(tipo);
                String carnes = (String) cbxCarnes.getSelectedItem();
                lblDescripcion.setText(carnes);
                String descuentos = (String) cbxDescuentos.getSelectedItem();
                lblUnidades.setText(descuentos);
                String desc = (String) cbxDescuentos.getSelectedItem();
                lblUnidades.setText(desc);
                mnuAagregar.setEnabled(false);
                mnuAcomprar.setEnabled(true);
                txtPrecio.setEnabled(true);

            }
            if (cbxCategorias.getSelectedItem() == "Abarrotes") {
                String tipo = (String) cbxCategorias.getSelectedItem();
                lblTipo.setText(tipo);
                String Abarrotes = (String) cbxAbarrotes.getSelectedItem();
                lblDescripcion.setText(Abarrotes);
                String IVA = (String) cbxIVA.getSelectedItem();
                lblUnidades.setText(IVA);
                mnuAagregar.setEnabled(false);
                mnuAcomprar.setEnabled(true);
                txtPrecio.setEnabled(true);

            }
            if (cbxCategorias.getSelectedItem() == "Carnes frias ") {
                String Tipo = (String) cbxCategorias.getSelectedItem();
                lblTipo.setText(Tipo);
                String frias = (String) cbxCarnesFrias.getSelectedItem();
                lblDescripcion.setText(frias);
                String uni = (String) cbxUnidades.getSelectedItem();
                lblUnidades.setText(uni);
                mnuAcomprar.setEnabled(true);
                mnuAagregar.setEnabled(false);
                mnuAcomprar.setEnabled(true);
                txtPrecio.setEnabled(true);
                txtPeso.setEnabled(true);
            }
        }

    }//GEN-LAST:event_mnuAagregarActionPerformed

    private void mnuAsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuAsalirActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= 48 && evt.getKeyChar() <= 58)
                || (evt.getKeyChar() == 8)) {
        } else {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten numeros.");
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAbarrotes;
    private javax.swing.JComboBox<String> cbxCarnes;
    private javax.swing.JComboBox<String> cbxCarnesFrias;
    private javax.swing.JComboBox<String> cbxCategorias;
    private javax.swing.JComboBox<String> cbxDescuentos;
    private javax.swing.JComboBox<String> cbxIVA;
    private javax.swing.JComboBox<String> cbxUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JLabel lblUnidades;
    private javax.swing.JMenuItem mnuAagregar;
    private javax.swing.JMenuItem mnuAcomprar;
    private javax.swing.JMenu mnuAgregar;
    private javax.swing.JMenuItem mnuAsalir;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
